services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py test employees/tests &&
      python manage.py create_admin && 
      uwsgi --ini /app/company/uwsgi.ini
      "
    volumes:
      - .:/app
      - static_volume:/app/static
    ports:
      - "8001:8001"
    env_file:
      - company/.env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./company_nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./company/uwsgi_params:/etc/nginx/uwsgi_params
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
